[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:backend"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1

[deploy.envs]
NODE_ENV = "production"
PORT = "3002" 