[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:backend"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
numReplicas = 1
healthcheckInterval = 30

[deploy.envs]
NODE_ENV = "production"
PORT = "3002"
DATABASE_URL = "${DATABASE_URL}"
JWT_SECRET = "${JWT_SECRET}" 