[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build:backend"

[deploy]
startCommand = "node dist/backend/main.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
numReplicas = 1
healthcheckInterval = 5
restartPolicyMaxRetries = 3
healthcheckInitialDelay = 10

[deploy.envs]
NODE_ENV = "production"
PORT = "3002"
DATABASE_URL = "${DATABASE_URL}"
JWT_SECRET = "${JWT_SECRET}"
NIXPACKS_NODE_VERSION = "18"
HOST = "0.0.0.0"
PRISMA_LOG_LEVEL = "error" 