[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:backend"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
numReplicas = 1
healthcheckInterval = 10
restartPolicyMaxRetries = 3
healthcheckInitialDelay = 15

[deploy.envs]
NODE_ENV = "production"
PORT = "3002"
DATABASE_URL = "${DATABASE_URL}"
JWT_SECRET = "${JWT_SECRET}"
NIXPACKS_NODE_VERSION = "18"
HOST = "0.0.0.0"
PRISMA_LOG_LEVEL = "error" 