[build]
builder = "nixpacks"
buildCommand = "npm run railway-build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
numReplicas = 1
healthcheckInterval = 15
restartPolicyMaxRetries = 5
healthcheckInitialDelay = 30

[deploy.envs]
NODE_ENV = "production"
PORT = "3002"
DATABASE_URL = "${DATABASE_URL}"
JWT_SECRET = "${JWT_SECRET}"
NIXPACKS_NODE_VERSION = "18"
HOST = "0.0.0.0"
PRISMA_LOG_LEVEL = "error"

[nixpacks]
start-command = "node dist/backend/main.js"
install-command = "npm install --production=false --no-optional"

[deploy.phases.build]
cmds = [
  "npm install --production=false --no-optional",
  "npm run railway-build",
  "npm run install-backend-deps",
  "npm run predeploy"
]

[deploy.phases.start]
cmd = "node dist/backend/main.js" 